apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v0tt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-v0tt@sha256:21e5af96528708a337dbae4fd1551d5ebae65afe9926fcb60c87ebe2b1069ac1
        name: my-nodejs
        resources: {}
status: {}
